---
# Install ims packages

- name: unwanted packages are removed
  package:
    name: "{{ ims_packages_remove }}"
    state: absent
  become: true
  when: ims_remove_packages

- name: prereq repositories are installed
  package:
    name: "{{ ims_packages_repos }}"
    state: "{{ ims_packages_state }}"
  become: true

- name: prereq packages are installed
  package:
    name: "{{ ims_packages_prereq }}"
    state: "{{ ims_packages_state }}"
  become: true

- name: packages are installed
  package:
    name: "{{ ims_packages_install }}"
    state: "{{ ims_packages_state }}"
  become: true
